### PR TITLE
Add support for using IAM role credentials

### PR DESCRIPTION
**Pull request by jessekempf**

### CODE REVIEW

**Comment by snoyberg** [comment]
This looks fine. However, can you:

* Make a major version bump in the cabal file
* Add a note in the changelog explaining the change

**Comment by jessekempf** [comment]
@snoyberg: by your command.

**Comment by snoyberg** [comment]
Thinking about this a bit more: do you have any objection if I make all of the fields in that data structure strict, that way anyone trying to compile against the new version of the library gets a compiler error instead of warning for the missing field?

**Comment by jessekempf** [comment]
@snoyberg: I see no problem in having all fields marked strict for a data structure that will have all its fields accessed during execution.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
