### PR TITLE
Add support for inline images, content-id headers, and an executable that accepts YAML input 

### PR DESCRIPTION
**Pull request by danchoi**
This patch adds:
1. Support for inlined Base64 encoded images. These are nested as parts inside `multipart/related` sections along with the HTML part in which the images should be inlined. The HTML can then embed the attached images using `` markup. The new code adds the Content-ID headers for these inlined image parts, which otherwise act like attachments.
2. An executable called `mime-mail`. This executable takes YAML or JSON on STDIN and generates a MIME message on standard output.

### CODE REVIEW

**Comment by snoyberg** [comment]
There's a lot of different stuff here, so it's difficult to review. Different concerns I have:

1. Can you break down where the API breakages occur?
2. Is it necessary to include the spec itself in the repo? That seems a bit strange.
3. Can the executable be put in a separate package? As it stands now, it's code that I'm not comfortable maintaining myself, and adds extra dependencies for all mime-mail users.

**Comment by danchoi** [comment]
You're right. I shouldn't have staged the whole thing. I'll try to reduce the pull request.

**Comment by danchoi** [comment]
I removed all the extra files and reduced the scope of the pull request to just the changes I made to the Network.Mail.Mime.hs file: https://github.com/snoyberg/mime-mail/pull/40/files

I created two new data types, PartContent and Disposition. I also made a new alternate constructor for Pair, CompoundPair (Heads, [Pair]) to allow nesting parts in a multipart/related section.

**Comment by snoyberg** [comment]
I think this PR could be improved with a rebase, but it's good enough to start looking over for now.

Since this is a breaking API change, I need to be methodical. There's also issue #36 (pinging @jonsterling) which I believe is asking for a similar change. Jon: could you look over the change in the API and see if it addresses the case you're looking at?

If the functionality provided is correct, we can look into the implementation next.

**Comment by jonsterling** [comment]
Thanks for pointing this out to me michael! I'll have a look as soon as I have got a free moment.

**Comment by snoyberg** [comment]
Awesome, thanks!

**Comment by jonsterling** [comment]
I have not looked too carefully at the individual code changes, but the restructuring of the `Part` type does indeed do a lot to bring the data structure used here more in line with the MIME standard. So I am at least nominally in favor of this pull request.

I would say, however, that my preference would be a library that gives straightforward data types which encode very directly the multipart mail format, as opposed to a data structure which captures several very common use-cases of it and gets interpreted/printed into a mime message.  Historically, this library has been very solidly in the latter camp, and even with this PR, it still remains on that side of things. Even if such an interface were to be retained, there is benefit in having at least a level of abstraction at which the structure of the data is precisely the same as the MIME standard.

**Comment by snoyberg** [comment]
@jonsterling Can you propose some improvements to what @danchoi has provided?

**Comment by jonsterling** [comment]
@snoyberg I think that this is a very solid step forward, and something along these lines may be the only way forward unless significant API disruption is intended; it would be interesting to experiment with something like what I proposed in my previous comment, but probably this is not the place to do it. So if we can verify that it actually does what is intended, then I'm fine with it.

**Comment by snoyberg** [comment]
Perhaps a step in the right direction is to stop exporting constructors from this module and instead just have smart constructor functions. That would allow us to overhaul the internal representation without a breaking change in the future. I realize that's a significant breaking change, but I think this PR already introduces quite a lot of user breakage (I'm guessing every program using this package would need to change).

One approach to minimizing impact would be:

* Introduce a new module in this package to provide abstract datatypes and smart constructors
* Minimally: make it feature-complete with this PR and release
* Continue to iterate on that module to make it closer to the spec
* Eventually: deprecate the original module, and after that replace it with the new one

@danchoi Would it work for you if this functionality ended up in a separate module to start off with?

**Comment by danchoi** [comment]
@snoyberg That seems to me like a good way forward. Let me know who you'd like to write the code for each piece of the next two steps in your list.

**Comment by snoyberg** [comment]
I'd be happy to work with you on the first two steps, which would probably get it done faster. I may not have time in the immediate future to work on this.

**Comment by snoyberg** [comment]
@vagifverdi Can you point me to your cleaned up branch?

**Comment by vagifverdi** [comment]
@snoyberg I did not do it on github, but on my local fork. I'll put it on github tonight.

**Comment by vagifverdi** [comment]
I added my pull request.

**Comment by MarekSuchanek** [comment]
Done in #53 (merged), if need more please make it on the top of that...

**Pull request closed without merging**
