### PR TITLE
Add support for inline images and content-id headers

### PR DESCRIPTION
**Pull request by vagifverdi**

### CODE REVIEW

**Comment by snoyberg** [comment]
The changes seem OK to me. I'll be honest: I'm not really using this library much these days, and wouldn't mind adding a co-maintainer. CC @danchoi and @jonsterling as well. I can merge and release (with appropriate version bump, `@since` comments, and `ChangeLog` updates added to this PR), but I'd also be happy to add one or two more maintainers who are more familiar with the spec than I am. Anyone interested?

**Comment by danchoi** [comment]
I'm willing to help maintain this library, since my company has a stake in developing it.

**Comment by danchoi** [comment]
FYI we are maintaining a fork at https://github.com/MackeyRMS/mime-mail as a company account and have incorporated @vagifverdi's changes. We would prefer to maintain the library as a company account rather than me individually.

**Comment by snoyberg** [comment]
I'm not aware of any way to grant commit access to an organization instead of individuals. I've sent you an invite to be a contributor to the repo, and can add others from MackeyRMS you'd like as well. If you let me know what your Hackage username is, I can give you maintainer access there too.

**Comment by danchoi** [comment]
I accepted the invite. My Hackage handle is DanielChoi

**Comment by snoyberg** [comment]
Alright, added on Hackage

**Comment by vshabanov** [comment]
So, will the updated version be released on Hackage?

**Comment by MarekSuchanek** [comment]
Hello @snoyberg, please how it looks with merging this and releasing a new version on Hackage? :grin: I need to use inline images and multipart/related in our project and I would like to avoid developing own wrapper around or forking the current mime-mail to achieve this...

**Comment by snoyberg** [comment]
From the discussion above, I thought @danchoi was going to take over merging and release to Hackage.

**Comment by MarekSuchanek** [comment]
From his punchcard, @danchoi seems to be a bit inactive...

In case of emergency, I can become a co-maintainer (for such chore tasks, dunno if development - maybe I could go through a bit during the summer). I am MarekSuchanek at Hackage - not so much stuff  there yet, but I sort of teach Haskell and I need this for our quite big project [ds-wizard/dsw-server](https://github.com/ds-wizard/dsw-server)...

**Comment by danchoi** [comment]
Hi sorry I’ve been MIA. marek’s help would be welcome. I don’t think I’ll have much free time.

**Comment by snoyberg** [comment]
Cool, @MarekSuchanek you've been added here on Github and on Hackage.

**Comment by MarekSuchanek** [comment]
Thanks! I will testing and merge this today/tomorrow, then create a new release...

**Pull request merged**
